
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xselabneytngumpnthvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzZWxhYm5leXRuZ3VtcG50aHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMjU2MzksImV4cCI6MjA1NzYwMTYzOX0.D6rtXjcvcGgSzXvi7wHE3aZRzqQNeDOJ4oP8oLCSxSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
